handle: stripe
isFrontendEnabled: true
name: Stripe
paymentType: purchase
settings:
  apiKey: sk_test_51Kl4WcSCbws3pPlWHmEM7yyyne0KpS0jfBJZhOQxuBSlEdF2C5ctnywrV6aaNaeI46xSqZOQUzzRKpu8hpUMrNzw00QhX9mBvV
  publishableKey: pk_test_51Kl4WcSCbws3pPlWphBNCVz1a83SbFVnvLopXzfraOkjT8KPgLlzA46YhdSMZju3cGB7UI4PW091fyDWtVeRp8Js0014uHzOLG
  sendReceiptEmail: ''
  signingSecret: crafcms_testing
sortOrder: 99
type: craft\commerce\stripe\gateways\PaymentIntents
